### ISSUE TITLE
Changing request interval fails

### ISSUE THREAD

**Issue by ododonov** [nicolasme/s7comm#2]
Hi!
It's me again) I think I fount another little bag.
So, in README you say:

```
Change the poll interval if needed in the cmd/main.go file

var pollInterval = flag.Duration("poll_interval", 10*time.Second, "how often to send metrics")
```

But if I change it to another value, program exits with fatal:

```
2021/08/05 10:12:19 I! Connexion successfull
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa826e8]

goroutine 10 [running]:
github.com/robinson/gos7.(*tcpTransporter).Send(0xc0000ead00, 0xc000039120, 0x1f, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/robinson/gos7@v0.0.0-20201216125248-2dd72fe148d3/tcpclient.go:117 +0x108
github.com/robinson/gos7.(*client).send(0xc00006cec0, 0xc00005fc78, 0x1f, 0xc000039120, 0x7)
        /go/pkg/mod/github.com/robinson/gos7@v0.0.0-20201216125248-2dd72fe148d3/client.go:469 +0x5a
github.com/robinson/gos7.(*client).readArea(0xc00006cec0, 0x84, 0x33e, 0x26, 0x1, 0x2, 0xc0001fe4b0, 0x4, 0x4, 0x4, ...)
        /go/pkg/mod/github.com/robinson/gos7@v0.0.0-20201216125248-2dd72fe148d3/client.go:228 +0x3a5
github.com/robinson/gos7.(*client).AGReadDB(...)
        /go/pkg/mod/github.com/robinson/gos7@v0.0.0-20201216125248-2dd72fe148d3/client.go:76
github.com/robinson/gos7.(*client).Read(0xc00006cec0, 0xc0001fe2c0, 0xd, 0xc0001fe4b0, 0x4, 0x4, 0x1010100458285, 0x0, 0x3, 0x0)
        /go/pkg/mod/github.com/robinson/gos7@v0.0.0-20201216125248-2dd72fe148d3/client.go:424 +0xa65
github.com/nicolasme/s7comm/plugins/inputs/s7comm.(*S7Comm).Gather(0xc000034d80, 0xcbd4b8, 0xc00006cf00, 0x0, 0x3)
        /etc/telegraf-plugins/s7comm/plugins/inputs/s7comm/s7comm.go:94 +0x10b
github.com/influxdata/telegraf/plugins/common/shim.(*Shim).startGathering(0xc0000eaa80, 0xcb7c78, 0xc000242300, 0xcb5ee8, 0xc000034d80, 0xcbd4b8, 0xc00006cf00, 0xee6b2800)
        /go/pkg/mod/github.com/influxdata/telegraf@v1.18.3/plugins/common/shim/input.go:95 +0x270
github.com/influxdata/telegraf/plugins/common/shim.(*Shim).RunInput.func1(0xc0000eaa80, 0xcb7c78, 0xc000242300, 0xcbd4b8, 0xc00006cf00, 0xee6b2800)
        /go/pkg/mod/github.com/influxdata/telegraf@v1.18.3/plugins/common/shim/input.go:46 +0x72
created by github.com/influxdata/telegraf/plugins/common/shim.(*Shim).RunInput
        /go/pkg/mod/github.com/influxdata/telegraf@v1.18.3/plugins/common/shim/input.go:45 +0x1e6
```

I found that it happens here (s7comm.go, string 94):

```
 _, err := s.client.Read(node.Address, buf)

```
I don't know Go at all, so I can't tell now, how to fix this. I want to search for decision of this, but I hope you may find it faster, because you know the language)

Thank you, have a nice day!

**Comment by racquemis** [comment]
Make sure the timeouts set in the configuration file are higher than the polling interval. then it will work.
